routes/web.php
<?php

Auth::routes();

Route::get('/', 'CarController@index')->name('home');

Route::resource('cars', 'CarController');

Route::group(['prefix' => 'car'], function(){
  Route::group(['prefix' => '{car}'], function($car){

    // Files
    Route::resource('tenencies', 'TenencyController');
    Route::resource('fines', 'FineController');
    Route::resource('services', 'ServiceController');
    Route::resource('documents', 'DocumentController');

  });
});

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    public function car()
    {
    	return $this->belongsTo(Car::class);
    }
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Document;
use Illuminate\Http\Request;
use App\Car;
use Illuminate\Support\Facades\Storage;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Car $car)
    {
        $documents = $car->documents();
        return view('document.index', compact('documents', 'car'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Car $car)
    {
        return view('document.create', compact('car'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Car $car)
    {
        $request->validate([
            'title' => 'required',
            'file' => 'required|file|max:2048',
        ]);

        $document = new document;
        $document->title = $request->title;
        $document->description = $request->description;
        $document->reference = $request->reference;
        $document->car_id = $car->id;

        if($request->has('file')){
            $file = $request->file('file');
            $filename = 'document-' . time() . '.' . $file->getClientOriginalExtension();
            $file->storeAs("public/documents/", $filename);

            $document->file = $filename;
        }

        if ($document->save()) {
            return redirect()
                ->route('documents.index', $car)
                ->with('msg', 'Documento registrado satisfactoriamente');
        }

        return redirect()
                ->route('documents.index', $car)
                ->withInput()
                ->with('msg', 'El documento NO pudo ser registrado');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function edit(Car $car,Document $document)
    {
        return view('document.edit', compact('car', 'document'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Car $car, Document $document)
    {
        $request->validate([
            'title' => 'required',
            'file' => 'file|max:2048',
        ]);

        $document->title = $request->title;
        $document->description = $request->description;
        $document->reference = $request->reference;

        if($request->has('file')){
            Storage::delete('public/documents/' . $document->file);

            $file = $request->file('file');
            $filename = 'document-' . time() . '.' . $file->getClientOriginalExtension();
            $file->storeAs("public/documents/", $filename);

            $document->file = $filename;
        }

        if ($document->save()) {
            return redirect()
                ->route('documents.index', $car)
                ->with('msg', 'Documento actualizado satisfactoriamente');
        }

        return redirect()
                ->route('documents.index', $car)
                ->withInput()
                ->with('msg', 'El documento NO pudo ser actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car,Document $document)
    {
        Storage::delete("public/documents/" . $document->file);

        if($document->delete()){
            return redirect()
                ->route('documents.index', $car)
                ->with('msg', 'Documento eliminado correctamente');
        }

        return redirect()
                ->route('documents.index', $car)
                ->with('msg', 'El documento NO se pudo eliminar');
    }
}

resources/views/document/partials/form-create.blade.php
{!! Form::open(['route' => ['documents.store', $car], 'files' => true]) !!}

	<div class="form-group row">
		<div class="col-md-6">
			<label for="title">Titulo:</label>
			{{ Form::text('title', null, ['placeholder' => 'Ingresa el titulo...', 'class' => 'form-control']) }}
		</div>
		<div class="col-md-6">
			<label for="reference">Referencia:</label>
			{{ Form::text('reference', null, ['placeholder' => 'Ingresa la referencia...', 'class' => 'form-control']) }}
		</div>
		<div class="col-md-12">
			<label for="description">Descripcion:</label>
			{{ Form::textarea('description', null, ['placeholder' => 'Ingresa el la description...', 'class' => 'form-control']) }}
		</div>
	</div>

	<div class="form-group">
			<label for="file">Archivo:</label>
			{{ Form::file('file') }}
	</div><hr>

	<div class="form-group text-center">
			<a href="{{ route('documents.index', $car) }}" class="btn btn-secondary">
				Regresar
			</a>
			<button type="submit" class="btn btn-primary">
				Guardar <i class="fas fa-save"></i>
			</button>
	</div>

{!! Form::close() !!}

resources/views/document/partials/form-edit.blade.php
{!! Form::open(['route' => ['documents.update', $car, $document], 'files' => true]) !!}

	<input type="hidden" name="_method" value="PUT">

	<div class="form-group row">
		<div class="col-md-6">
			<label for="title">Titulo:</label>
			{{ Form::text('title', $document->title, ['placeholder' => 'Ingresa el titulo...', 'class' => 'form-control']) }}
		</div>
		<div class="col-md-6">
			<label for="reference">Referencia:</label>
			{{ Form::text('reference', $document->reference, ['placeholder' => 'Ingresa la referencia...', 'class' => 'form-control']) }}
		</div>
		<div class="col-md-12">
			<label for="description">Descripcion:</label>
			{{ Form::textarea('description', $document->description, ['placeholder' => 'Ingresa el la description...', 'class' => 'form-control']) }}
		</div>
	</div>

	<div class="form-group">
		@if($document->file)
            <a href="{{ asset("storage/documents/" . $document->file) }}" target="_blank" class="btn btn-sm btn-info">{{ $document->file }}</a>
        @endif
			<label for="file">Archivo:</label>
			{{ Form::file('file') }}
	</div><hr>

	<div class="form-group text-center">
			<a href="{{ route('documents.index', $car) }}" class="btn btn-secondary">
				Regresar
			</a>
			<button type="submit" class="btn btn-primary">
				Actualizar <i class="fas fa-save"></i>
			</button>
	</div>

{!! Form::close() !!}

resources/views/document/partials/table.blade.php
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Titulo</th>
            <th>Descripcion</th>
            <th>Referencia</th>
            <th>Registrada</th>
            <th>Actualizada</th>
            <th>Archivo</th>
            <th>Acciones</th>
        </tr>
    </thead>

    @forelse($documents as $document)
        <tr>
            <td>{{ $loop->index + 1 }}</td>
            <td>{{ $document->title }}</td>
            <td>{{ $document->description }}</td> 
            <td>{{ $document->reference }}</td>
            <td>{{ $document->created_at->format('d/m/Y') }}</td>
            <td>{{ $document->updated_at->format('d/m/Y') }}</td>
            <td>
                @if($document->file)
                    <a href="{{ asset("storage/documents/" . $document->file) }}" target="_blank" class="btn btn-sm btn-info">{{ $document->file }}</a>
                @endif
            </td>
            <td class="text-nowrap">
                <a href="{{ route('documents.edit', [$car, $document]) }}" class="btn btn-sm btn-success">
                    <i class="fas fa-pencil-alt"></i>
                </a>
                <a class="btn btn-sm btn-danger" href="#"
                   onclick="event.preventDefault();
                                 document.getElementById('delete-{{ $document->id }}').submit();">
                    <i class="fas fa-trash-alt"></i>
                </a>

                <form id="delete-{{ $document->id }}" action="{{ route('documents.destroy', [$car, $document]) }}" method="POST" style="display: none;">
                    @csrf
                    <input type="hidden" name="_method" value="DELETE">
                </form></td>
        </tr>
    @empty
        <tr>
            <td colspan="9">
                <p class="alert alert-info">No tienes Documentos</p>
            </td>

        </tr>
    @endforelse
</table>