routes/web.php
<?php

Auth::routes();

Route::get('/', 'CarController@index')->name('home');

Route::resource('cars', 'CarController');

Route::group(['prefix' => 'car'], function(){
  Route::group(['prefix' => '{car}'], function($car){

    // Files
    Route::resource('tenencies', 'TenencyController');
    Route::resource('fines', 'FineController');
    Route::resource('services', 'ServiceController');
    Route::resource('documents', 'DocumentController');

  });
});

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    public function car()
    {
    	return $this->belongsTo(Car::class);
    }
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Document;
use Illuminate\Http\Request;
use App\Car;
use Illuminate\Support\Facades\Storage;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Car $car)
    {
        $documents = $car->documents();
        return view('document.index', compact('documents', 'car'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Car $car)
    {
        return view('document.create', compact('car'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Car $car)
    {
        $request->validate([
            'title' => 'required',
            'file' => 'required|file|max:2048',
        ]);

        $document = new document;
        $document->title = $request->title;
        $document->description = $request->description;
        $document->reference = $request->reference;
        $document->car_id = $car->id;

        if($request->has('file')){
            $file = $request->file('file');
            $filename = 'document-' . time() . '.' . $file->getClientOriginalExtension();
            $file->storeAs("public/documents/", $filename);

            $document->file = $filename;
        }

        if ($document->save()) {
            return redirect()
                ->route('documents.index', $car)
                ->with('msg', 'Documento registrado satisfactoriamente');
        }

        return redirect()
                ->route('documents.index', $car)
                ->withInput()
                ->with('msg', 'El documento NO pudo ser registrado');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function edit(Car $car,Document $document)
    {
        return view('document.edit', compact('car', 'document'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Car $car, Document $document)
    {
        $request->validate([
            'title' => 'required',
            'file' => 'file|max:2048',
        ]);

        $document->title = $request->title;
        $document->description = $request->description;
        $document->reference = $request->reference;

        if($request->has('file')){
            Storage::delete('public/documents/' . $document->file);

            $file = $request->file('file');
            $filename = 'document-' . time() . '.' . $file->getClientOriginalExtension();
            $file->storeAs("public/documents/", $filename);

            $document->file = $filename;
        }

        if ($document->save()) {
            return redirect()
                ->route('documents.index', $car)
                ->with('msg', 'Documento actualizado satisfactoriamente');
        }

        return redirect()
                ->route('documents.index', $car)
                ->withInput()
                ->with('msg', 'El documento NO pudo ser actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car,Document $document)
    {
        Storage::delete("public/documents/" . $document->file);

        if($document->delete()){
            return redirect()
                ->route('documents.index', $car)
                ->with('msg', 'Documento eliminado correctamente');
        }

        return redirect()
                ->route('documents.index', $car)
                ->with('msg', 'El documento NO se pudo eliminar');
    }
}

resources/views/document/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
        <h3><i class="fas fa-id-card fa-2x"></i> Documentos <small>Nueva documento</small></h3>
            <div class="card">
                <div class="card-header">
                    @include('partials.errors')
                </div>

                <div class="card-body">
                    @include('document.partials.form-create')
                </div>

                
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/document/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
        <h3><i class="fas fa-id-card fa-2x"></i> Documentos <small>Editar documentos</small></h3>
            <div class="card">
                <div class="card-header">
                    @include('partials.errors')
                </div>

                <div class="card-body">
                    @include('document.partials.form-edit')
                </div>

                
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/document/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
        <h3><i class="fas fa-id-card fa-2x"></i> Documentos</h3>
            <div class="card">
                <div class="card-header">
                    <h3>Documentos de {{ $car->brand }} <span class="badge badge-light">{{ $car->plate }}</span>
                    <a href="{{ route('documents.create', $car) }}" class="btn btn-warning float-right">
                    + Agregar
                    </a> </h3>
                </div>

                <div class="card-body">
                    @include('document.partials.table')
                    </div>

                    <div class="card-footer text-center">
                        <a href="{{ route('cars.show', $car) }}" class="btn btn-secondary">
                            <i class="fas fa-chevron-circle-left"></i> Regresar
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection