routes/web.php
<?php

Auth::routes();

Route::get('/', 'CarController@index')->name('home');

Route::resource('cars', 'CarController');

Route::group(['prefix' => 'car'], function(){
  Route::group(['prefix' => '{car}'], function($car){

    // Files
    Route::resource('tenencies', 'TenencyController');
    Route::resource('fines', 'FineController');
    Route::resource('services', 'ServiceController');
    Route::resource('documents', 'DocumentController');

  });
});

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    public function user()
    {
    	return $this->belongsTo(User::class);
    }
    
    public function tenencies()
    {
        return $this->hasMany(Tenency::class)->get();
    }

    public function fines()
    {
        return $this->hasMany(Fine::class)->get();
    }

    public function services()
    {
        return $this->hasMany(Service::class)->get();
    }

    public function documents()
    {
        return $this->hasMany(Document::class)->get();
    }
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Car;
use Illuminate\Support\Facades\Storage;

class CarController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $cars = auth()->user()->cars;
        return view('car.index', compact('cars'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('car.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'plate' => 'required|unique:cars',
            'model' => 'required|integer',
            'brand' => 'required',
            'color' => 'required',
            'image' => 'required|file|image|mimes:jpeg,jpg,png,gif,webp|max:2048',
        ]);

        $file = $request->file('image');
        $filename = 'car-' . time() . '.' . $file->getClientOriginalExtension();
        $file->storeAs("public/cars/", $filename);

        $car = new Car;
        $car->plate = $request->plate;
        $car->model = $request->model;
        $car->brand = $request->brand;
        $car->color = $request->color;
        $car->image = $filename;
        $car->user_id = auth()->user()->id;

        if($car->save()){
            return redirect()
                ->route('home')
                ->with('msg', 'Coche dado de alta correctamente');
        }

        return redirect()
            ->route('cars.create')
            ->withInput()
            ->with('msg', 'El coche NO pudo ser dado de alta!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Car $car)
    {
        return view('car.show', compact('car'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Car $car)
    {
        return view('car.edit', compact('car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Car $car)
    {
        $request->validate([
            'plate' => 'required',
            'model' => 'required|integer',
            'brand' => 'required',
            'color' => 'required',
            'image' => 'file|image|mimes:jpeg,jpg,png,gif,webp|max:2048',
        ]);

        $car->plate = $request->plate;
        $car->model = $request->model;
        $car->brand = $request->brand;
        $car->color = $request->color;
        
        if ($request->has('image')) {
            Storage::delete("public/cars/" . $car->image);

            $file = $request->file('image');
            $filename = 'car-' . time() . '.' . $file->getClientOriginalExtension();
            $file->storeAs("public/cars/", $filename);

            $car->image = $filename;
        }
        
        if($car->save()){
            return redirect()
                ->route('home')
                ->with('msg', 'Coche actualizado correctamente');
        }

        return redirect()
            ->route('cars.edit', $car)
            ->withInput()
            ->with('msg', 'El coche NO pudo ser actualizado!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car)
    {
        Storage::delete("public/cars/" . $car->image);

        if($car->delete()){
            return redirect()
                ->route('home')
                ->with('msg', 'Coche eliminado correctamente');
        }

        return redirect()
                ->route('home')
                ->with('msg', 'El coche NO eliminado');
    }
}

resources/views/car/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                	Cars App [Nuevo Coche]
                	@include('partials.errors')
                </div>

                <div class="card-body">
                	@include('car.form-create')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/car/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                	Cars App [Editar Coche]
                	@include('partials.errors')
                </div>

                <div class="card-body">
                	@include('car.form-edit')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/car/form-create.blade.php
{!! Form::open(['route' => 'cars.store', 'files' => true]) !!}

	<div class="form-group">
			<label for="plate">Placas:</label>
			{{ Form::text('plate', null, ['placeholder' => 'Ingresa las placas...', 'class' => 'form-control']) }}
	</div>

	<div class="form-group">
			<label for="model">Model:</label>
			{{ Form::number('model', date('Y'), ['min' => 2000, 'max' => 2050, 'class' => 'form-control']) }}
	</div>

	<div class="form-group">
			<label for="brand">Marca:</label>
			{{ Form::text('brand', null, ['placeholder' => 'Ingresa la marca...', 'class' => 'form-control']) }}
	</div>

	<div class="form-group">
			<label for="color">Color:</label>
			<input type="color" name="color" class="form-control">
	</div>

	<div class="form-group">
			<label for="image">Imagen:</label>
			{{ Form::file('image') }}
	</div><hr>

	<div class="form-group text-center">
			<a href="{{ route('home') }}" class="btn btn-secondary">
				Regresar
			</a>
			<button type="submit" class="btn btn.primary">
				Guardar
			</button>
	</div>

{!! Form::close() !!}

resources/views/car/form-edit.blade.php
{!! Form::open(['route' => ['cars.update', $car], 'files' => true]) !!}

	<input type="hidden" name="_method" value="PUT">

	<div class="form-group">
			<label for="plate">Placas:</label>
			{{ Form::text('plate', $car->plate, ['placeholder' => 'Ingresa las placas...', 'class' => 'form-control']) }}
	</div>

	<div class="form-group">
			<label for="model">Model:</label>
			{{ Form::number('model', $car->model, ['min' => 2000, 'max' => 2050, 'class' => 'form-control']) }}
	</div>

	<div class="form-group">
			<label for="brand">Marca:</label>
			{{ Form::text('brand', $car->brand, ['placeholder' => 'Ingresa la marca...', 'class' => 'form-control']) }}
	</div>

	<div class="form-group">
			<label for="color">Color:</label>
			<input type="color" value="{{ $car->color }}" name="color" class="form-control">
	</div>

	<div class="form-group">
			<label for="image">Imagen:</label>
			<img src="{{ asset("storage/cars/" . $car->image) }}">
			{{ Form::file('image') }}
	</div><hr>

	<div class="form-group text-center">
			<a href="{{ route('home') }}" class="btn btn-secondary">
				Regresar
			</a>
			<button type="submit" class="btn btn.primary">
				Actualizar
			</button>
	</div>

{!! Form::close() !!}

resources/views/car/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Cars App 
                    <a href="{{ route('cars.create') }}" class="btn btn-warning">
                    + Car
                    </a> 
                </div>

                <div class="card-body">
                    <div class="card-columns">
                        @forelse($cars as $car)
                            <div class="card bg-dark text-white">
                                <img class="card-img-top" src="{{ asset("storage/cars/" . $car->image) }}" alt="Card image cap">
                                <div class="card-body">
                                    <p><b>Placas:</b> {{ $car->plate }}</p>
                                    <p><b>Marca:</b> {{ $car->brand }}</p>
                                    <p><b>Modelo:</b> {{ $car->model }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    
                                    <a href="{{ route('cars.show', $car) }}" class="btn btn-info">
                                        <i class="fas fa-eye"></i>
                                    </a>

                                    <a href="{{ route('cars.edit', $car) }}" class="btn btn-warning">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>

                                    <a class="btn btn-danger" href="#"
                                       onclick="event.preventDefault();
                                                     document.getElementById('delete-{{ $car->id }}').submit();">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>

                                    <form id="delete-{{ $car->id }}" action="{{ route('cars.destroy', $car) }}" method="POST" style="display: none;">
                                        @csrf
                                        <input type="hidden" name="_method" value="DELETE">
                                    </form>
                                </div>
                            </div>
                        @empty
                            No tienes coches
                        @endforelse
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/car/nav.blade.php
<div class="list-group">
	  <a href="{{ route('tenencies.index', $car) }}" class="list-group-item list-group-item-action list-group-item-dark">
	    <i class="fas fa-id-card fa-2x"></i> Tenencias
	  </a>
	  <a href="{{ route('fines.index', $car) }}" class="list-group-item list-group-item-action list-group-item-dark">
	  	<i class="fas fa-file-invoice-dollar fa-2x"></i> Multas
	  </a>
	  <a href="#" class="list-group-item list-group-item-action list-group-item-dark">
	  	<i class="fas fa-tools fa-2x"></i> Verificaciones
	  </a>
	  <a href="{{ route('services.index', $car) }}" class="list-group-item list-group-item-action list-group-item-dark">
	  	<i class="fas fa-wrench fa-2x"></i> Servicios
	  </a>
	  <a href="{{ route('documents.index', $car) }}" class="list-group-item list-group-item-action list-group-item-dark">
	  	<i class="fas fa-file-alt fa-2x"></i> Documentos
	  </a>
</div>

resources/views/car/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-4">
            @include('car.nav')
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h4>{{ $car->brand }}</h4>
                </div>

                <div class="card-body">
                    <div class="card bg-dark text-white">
                        <img class="card-img-top" src="{{ asset("storage/cars/" . $car->image) }}" alt="Card image cap">
                        <div class="card-body">
                            <p><b>Placas:</b> {{ $car->plate }}</p>
                            <p><b>Marca:</b> {{ $car->brand }}</p>
                            <p><b>Modelo:</b> {{ $car->model }}</p>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection